import { z } from 'zod'

export const leadSchema = z.object({
    purpose: z.string().min(1),
    purposeOther: z.string().min(1),
    specificHelp: z.string().min(1),
    street: z.string().min(1),
    city: z.string().min(1),
    ownerName: z.string().min(1),
    ownerPhoneNumber: z.string().min(1),
    propertyAddress: z.string().min(1),
    ownerRelationship: z.string().min(1),
    contactName: z.string().min(1),
    contactPhone: z.string().min(1),
    contactEmail: z.string().email({ message: 'Invalid email address' }),
    bedrooms: z.number(),
    bathrooms: z.number(),
    homeowner: z.string(),
    timeline: z.string(),
    type: z.string(),
    unit: z.string(),
    referralName: z.string().min(1),
    homeType: z.string().min(1),
    referrerName: z.string().min(1),
    referrerPhone: z.string().min(1),
    referrerEmail: z.string().email({ message: 'Invalid email address' }),
})
